[versions]
commonsJexl = "2.1.1"
coreSplashscreen = "1.0.0"
kotlinCompilerExtensionVersion = "1.5.6"

androidCore = "1.9.1"
annotation = "1.7.1"
appcompat = "1.6.1"
constraintlayout = "2.1.4"
designSystem = "0.2-20240314.101140-42"
espressoCore = "3.5.1"
flipper-module = "0.161.0"
flipper-network = "0.161.0"
gradle = "8.2.2"
kotlin = '1.9.21'
junit = "4.13.2"
ktlintGradle = "11.5.1"
legacySupportV4 = "1.0.0"
lifecycleExtensions = "2.2.0"
material = "1.11.0"
compose = "1.5.4"
composeConstraintLayout = "1.0.1"

multidex = "2.0.1"
ruleEngine = "2.1.9"
material3 = "1.1.1"
runner = "1.5.2"
soloader = "0.10.4"
desugar_jdk_libs = "2.0.3"

[libraries]

android-core = { module = "org.hisp.dhis:android-core", version.ref = "androidCore" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
commons-jexl = { module = "org.apache.commons:commons-jexl", version.ref = "commonsJexl" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
dhis2-mobile-designsystem = { group = "org.hisp.dhis.mobile", name = "designsystem", version.ref = "designSystem" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
flipper-module = { module = "com.facebook.flipper:flipper", version.ref = "flipper-module" }
flipper-network = { module = "com.facebook.flipper:flipper-network-plugin", version.ref = "flipper-network" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
junit = { module = "junit:junit", version.ref = "junit" }
ktlint-gradle = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlintGradle" }
kotlinPlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinSerialization = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "compose" }
androidx-compose = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "composeConstraintLayout" }
androidx-compose-uitooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-compose-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-compose-viewbinding = { group = "androidx.compose.ui", name = "ui-viewbinding", version.ref = "compose" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
rule-engine = { module = "org.hisp.dhis.rules:rule-engine", version.ref = "ruleEngine" }
runner = { module = "androidx.test:runner", version.ref = "runner" }
soloader = { module = "com.facebook.soloader:soloader", version.ref = "soloader" }
desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar_jdk_libs" }

[plugins]

[bundles]
uicomponents-api = ["dhis2-mobile-designsystem"]